### PR TITLE
fix: Various errors working with `file` protocol

### PR DESCRIPTION
**Pull request by ReubenFrankel**
A note on `KeyError: 'LastModified'`: I'm assuming I encountered this error because I'm on a Unix-like OS (Ubuntu) and not Windows? I couldn't find a suitable replacement, so just indicate `null` for `updated_at` if it can't find a `LastModified` value.

### CODE REVIEW

**Comment by ReubenFrankel** [comment]
I also had a bit of a hard time with development setup because `poetry.lock` is not commited. Do you mind doing this? :slightly_smiling_face:

**Review by radbrt — APPROVED** [review]
Thank you!

**Comment by radbrt** [comment]
@ReubenFrankel I added the lockfile, and resolved a dependency bug along the way. I hadn't even gotten around to using poetry here.

**Comment by ReubenFrankel** [comment]
> @ReubenFrankel I added the lockfile, and resolved a dependency bug along the way. I hadn't even gotten around to using poetry here.

Thanks!

**Pull request merged**
